version: "2"
services:
  stream-reactor:
    image: streamreactorcassandra:latest
    build:
      context: ./
      args:
        BASE_VERSION: 1.2.1
        STREAM_REACTOR_COMPONENT: cassandra
        STREAM_REACTOR_VERSION: 1.2.1
        KAFKA_VERSION: 2.1.0
      dockerfile: ./Dockerfile